env:
  global:
    # directory containing the project source
    - REPO_DIR=.
    # pip dependencies to _build_ project
    - BUILD_DEPENDS="Cython setuptools>=25 setuptools_scm setuptools_scm_git_archive"
    # pip dependencies to _test_ project
    - TEST_DEPENDS="sympy pytest"
    - PLAT=x86_64
    - UNICODE_WIDTH=32
    - TWINE_USERNAME="anthrotype"
    - secure: sX3wbNcie0SOjV9r/7IqkmqDlBY5trhFLIGUzQmo0gdiKxSWM/07HkIbAHhXZB/nINkXGtWuhNdE3OQsh6MilODU5krE8hOOvfhh2lyrWVFk8BQstyeKZVlhGRX8GQfOViaOBncybnqPR5ovmAAo0whg+8qtL+kCE7MtmvG9WAQeeyhu45lg25ac/ZrUkJv1y/rjW9EuRDidGquU/1xcRe3s1H/2OnVvWaUgbU2KwTWQ2DRnXXeMdP3OgY8o818c7utjCt+gGaDmJgoJH0Bz8OiuNAZJrODp/0L/LeLDzyoI0Yc3osDlv5xnJq7Fsyer1ihV6ZuAaXZU1TkJvH4B5CeMWIUcWLxA3sOrAn3DDMO3ZdvsvYPOaCuI/k/4RCPZyV57h76Ibm6Qir71Fe4oNpIRiQm/zfD2H6Ez+E1R0u4SgPRsPFsD/YGF58vvP8KHliTMJCM27p5+ai6+ZDB0r7sLRVk0w/HLElRMNmpIcCEDcIjkZS95xffxRcQSXvj1otDDGcNxao4OxPdzbt2zIUZgsN+5uFjA3A0iAWwXd1/Auy11uqG+abDTxg5mAxQ0ovVsvL3Mle6CfvEp7e1mvpHxZRFARpjTH24Gt8nGGcakLeddhy43z0jpJxmYVxnPloDHTbSzvRnubwY0oIe3cZSbcxSJh1qWdzD66FNul5c=

# Travis only clones the latest 50 commits. We need the full repository to
# compute the version string from the git metadata:
# https://github.com/travis-ci/travis-ci/issues/3412#issuecomment-83993903
# https://github.com/pypa/setuptools_scm/issues/93
git:
  depth: 9999999

language: generic
dist: xenial
services: docker

matrix:
  include:
    - os: linux
      env: MB_PYTHON_VERSION=2.7
    - os: linux
      env:
        - MB_PYTHON_VERSION=2.7
        - UNICODE_WIDTH=16
    - os: linux
      env:
        - MB_PYTHON_VERSION=2.7
        - PLAT=i686
    - os: linux
      env:
        - MB_PYTHON_VERSION=2.7
        - PLAT=i686
        - UNICODE_WIDTH=16
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.5
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.5
        - PLAT=i686
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.6
        - BUILD_SDIST=true
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.6
        - PLAT=i686
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.7
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.7
        - PLAT=i686
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.8
    - os: linux
      env:
        - MB_PYTHON_VERSION=3.8
        - PLAT=i686
    - os: osx
      env:
        - MB_PYTHON_VERSION=2.7
    - os: osx
      env:
        - MB_PYTHON_VERSION=3.5
    - os: osx
      env:
        - MB_PYTHON_VERSION=3.6
    - os: osx
      env:
        - MB_PYTHON_VERSION=3.7
    - os: osx
      env:
        - MB_PYTHON_VERSION=3.8

before_install:
  - source multibuild/common_utils.sh
  - source multibuild/travis_steps.sh
  - before_install

install:
  - build_wheel $REPO_DIR $PLAT

script:
  - install_run $PLAT

after_success:
  # if tagged, upload wheels (and sdist) to PyPI
  - |
    if [ -n "$TRAVIS_TAG" ] && [ "$TRAVIS_REPO_SLUG" == "fonttools/pyclipper" ]; then
      pip install --upgrade twine
      twine upload wheelhouse/*.whl
      if [ "$BUILD_SDIST" == true ]; then
        pip install --upgrade cython setuptools
        python setup.py sdist
        twine upload dist/*.zip
      fi
    fi
